spring:
  mvc:
    static-path-pattern: /**                #所有的访问都要通过这里
  resources:
    static-locations: classpath:/static/    #静态资源文件位置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable-springboot2?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
server:
  port: 9200
flowable:
  common:
    app:
      idm-url: index.html
  idm:
    enabled: true
  #自动部署验证设置 true:开启（默认）/false：关闭
  check-process-definitions: true
  activity-font-name: "宋体"
  label-font-name: "宋体"
  annotation-font-name: "宋体"
  #关闭定时任务JOB
  async-executor-activate: false
  #将databaseSchemaUpdate设置为true。
  #当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true

