spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable-springboot?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
mybatis:
  mapper-locations: classpath:/mapper/*
server:
  port: 9200
flowable:
  idm:
    enabled: true
