CREATE TABLE `act_creation` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROCESS_DEFINITION_ID` varchar(255) DEFAULT NULL COMMENT '流程定义id',
  `DOUSERID` varchar(20) DEFAULT NULL COMMENT '操作人id',
  `ACT_ID` varchar(64) DEFAULT NULL,
  `PROCESS_INSTANCE_ID` varchar(255) NOT NULL DEFAULT '0' COMMENT '流程实例id',
  `PROPERTIES_TEXT` varchar(2000) DEFAULT NULL COMMENT '参数',
  `STATE_` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0代表有效 1代表无效',
  `create_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='临时创建活动节点';